### ISSUE TITLE
Create a Docker container file  (Dockerfile) for running the api project.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#10]
Use a base image probably debian/ubuntu/slim or similar to create the docker contianer where the app will run.
Create docker-compose.yaml file to start and stop container.

Need to add docker-compose to your local envs as well Angel and Eziel. This tool is very important.

Depends on other existing issue and should be done once these are done: 
1. https://github.com/Sesame-Disk/cool-storage-api/issues/6
2. https://github.com/Sesame-Disk/cool-storage-api/issues/5

Story points: 3

**Comment by ezielramos** [comment]
# Dockerfile
