### ISSUE TITLE
Desktop environment and tech stack setup basic definition. 

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#2]
Things to define for windows:
- OK. Golang 1.18.
- Ok. Docker para windows latest.
- OK. vscode latest.
- (Pending.) Specific dependencies for reactjs to be defined, versions of packages, etc. 
- (Pending) Plugins required for VSCODE vscode 
- Ok. mySQL 8.
- (Panding) Version of the AWS SDK.
- LDAP connection libraries?
- Gin Version?
- Others?

El objetivo es tener una version de un paquete fija o tener idea de cuales son las opciones y luego crear un issue para investigar esas opciones en futuros sprints.

**Comment by alvaldes** [comment]
### Windows Setup
* OK. Golang 1.18.+
* Ok. Docker latest.
* OK. vscode latest.
* (Pending.) Specific dependencies for reactjs to be defined, versions of packages, etc.
   * Define a UI library (Tailwind, Chakra-UI, Material UI, Bootstrap) 
* (Pending) Plugins required for VSCODE:   
   * JavaScript (ES6) code snippets
   * npm
   * ES7+ React/Redux/React-Native snippets
   * React Extension Pack
   * Reactjs code snippets
   * Simple React Snippets
   * Go
* Ok. mySQL 8.
* (Panding) Version of the AWS SDK.
* LDAP connection libraries?
* Gin Version?
* Others?

**Comment by aguzmans** [comment]
Good job thanks.
