### ISSUE TITLE
create MySQL configs parameters to be loaded from YAML.

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#21]
We need to have the yaml config contain all necessary config parameters and golang code to load those.

notice example: 

1. Call config function: https://github.com/aguzmans/cool-storage/blob/master/main.go#L27
2. Config read config definition: https://github.com/aguzmans/cool-storage/blob/master/configread/read-dot-conf.go
3. the YAML: https://github.com/aguzmans/cool-storage/blob/master/conf/cool-api.yaml

related to this PR: https://github.com/Sesame-Disk/cool-storage-api/pull/15/files

Story points: 3

**Comment by alvaldes** [comment]
done
