### ISSUE TITLE
Config Glacier to link connection

### ISSUE THREAD

**Issue by alvaldes** [Sesame-Disk/cool-storage-api#29]
Objective: Add to [cool-api.yml](https://github.com/Sesame-Disk/cool-storage-api/blob/main/conf/cool-api.yaml) the configuration to access AWS Glacier

Story Points: 2

**Comment by abelguzman** [comment]
FYI: AWS has a few ways to authenticate for programs. the two main ones are key/secret pair and assume role with privileges. We will start using key/pair as is easier to understand, but in the future we will move on to roles as is more scalable and secure.

**Comment by alvaldes** [comment]
closed and continue [here](https://github.com/Sesame-Disk/cool-storage-api/issues/44)
