### ISSUE TITLE
Create the .gitignore file Golang Project

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#6]
File for git to ignore files (.gitignore)
What should never be public about this project; 

1. Secrets.
2. Environment files.
3. Binaries.

Story points: 1

**Comment by ezielramos** [comment]
# gitignore file Golang Proyect
'''
# ignore ALL .log files
*.log

# ignore ALL files in ANY directory named temp
temp/

# ignore ALL .exe files
*.exe
'''

**Comment by alvaldes** [comment]
Take a look at this [Go.ignorefile](https://github.com/github/gitignore/blob/main/Go.gitignore) file, here are some others binaries and test logs files to exclude from git
