### ISSUE TITLE
Choose the technology to use for MySQL

### ISSUE THREAD

**Issue by aguzmans** [Sesame-Disk/cool-storage-api#8]
Objective; Use a single library for MySQl connections.

There are two very popular libraris for MySQL; GORM and [go-sql-driver/mysql](https://github.com/go-sql-driver/mysql), We need to chose one of them And feel free to consider another-one.

Final result is a recommendation or evaluation of how to chose. 

Story points: 3

**Comment by ezielramos** [comment]
# Connect GoLang and MySQL

# Library github.com/go-sql-driver/mysql

**Comment by aguzmans** [comment]
Thanks for the recommendation. it will be adopted because of the following reasons:

1. Other Team members know both libraries, but others are very new to Golang. Both librarias imply that people need to learn to use them. Then GORM will crate a learning curve higher on a team that already has many other things to learn. Therefore `github.com/go-sql-driver/mysql` will be easier to understand to get started with. This decision has pros and cons. Simple is better.
2. Growth wise GORM would make it easier and scalable once people already understand the tech to certain extent. Then this will allow faster development up to medium size user scale project (10K to 100K user is or somewhere in between some automatically generated querries will start performing BADLY). This mean at some point in the future if this project becomes popular and runs large envs we would need to change much of the magic of GORM to specific queries more like the style of `github.com/go-sql-driver/mysql`. I am saying this based on the expectations we have about the project and the fact that we will use it to provide cloud services to real customers possibly on a global scale.
